// <auto-generated />
using ApiPelicula.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiPelicula.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250630033524_Agregando Seeder")]
    partial class AgregandoSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiPelicula.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Nombre = "Accion"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Aventura"
                        },
                        new
                        {
                            Id = 30,
                            Nombre = "Comedia"
                        },
                        new
                        {
                            Id = 40,
                            Nombre = "Drama"
                        },
                        new
                        {
                            Id = 50,
                            Nombre = "Fantasia"
                        },
                        new
                        {
                            Id = 60,
                            Nombre = "Ciencia Ficcion"
                        },
                        new
                        {
                            Id = 70,
                            Nombre = "Terror"
                        },
                        new
                        {
                            Id = 80,
                            Nombre = "Romance"
                        });
                });

            modelBuilder.Entity("ApiPelicula.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estreno")
                        .HasColumnType("int");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Sinopsis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.HasIndex("Titulo")
                        .IsUnique();

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("ApiPelicula.Models.Movie", b =>
                {
                    b.HasOne("ApiPelicula.Models.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });
#pragma warning restore 612, 618
        }
    }
}
